# See (TODO): https://hackage.haskell.org/package/turtle
name: offlineimapgenerator
version: 0.0.0.1
synopsis: Generator for offlineimap that updates certificate fingerprints.
description: |
    Generator for offlineimap that updates certificate fingerprints by
    reading a template file and writing a result file (with updated
    fingerprints).
category: HTML, CSV
license: GPL-3
stability: development

ghc-options:
- -Wall
- -fno-warn-unused-do-bind
- -fno-warn-name-shadowing
- -fno-warn-missing-signatures
- -fno-warn-type-defaults
- -fno-warn-orphans

library:
  source-dirs: src
  dependencies:
    - base
    - foldl
    - publicsuffix
    - text
    - turtle

executables:
  offlineimapgenerator:
    main: Main.hs
    source-dirs: app
    ghc-options: [-threaded]
    dependencies:
    - base
    - optparse-applicative
    - offlineimapgenerator
